// Generated by tools/generate_settings.py. Do not edit.
#pragma once

#include <cstdint>
#include <span>
#include <string>
#include <string_view>
#include <variant>

namespace HouseRules::SettingsCatalog
{
	enum class ValueType : std::uint8_t { kBool, kFloat, kInt, kString };
	using Value = std::variant<bool, double, std::int64_t, std::string>;

	struct Descriptor
	{
		std::string_view id;
		std::string_view section;
		std::string_view key;
		ValueType type;
		Value defaultValue;
		bool exposed;
		std::string_view pageId;
		std::string_view pageName;
		std::string_view pageSummary;
		std::string_view group;
		std::string_view label;
		std::string_view help;
		std::string_view control;
		double minimum;
		double maximum;
		double step;
		bool hasRange;
		std::string_view options;
		std::int32_t sortKey;
		Value (*read)();
		bool (*write)(const Value&);
	};

	struct Page
	{
		std::string_view id;
		std::string_view name;
		std::string_view summary;
		std::int32_t sortKey;
		std::string_view categoryId;
	};

	struct Category
	{
		std::string_view id;
		std::string_view name;
		std::int32_t sortKey;
	};

	[[nodiscard]] std::span<const Descriptor> All() noexcept;
	[[nodiscard]] std::span<const Page> Pages() noexcept;
	[[nodiscard]] std::span<const Category> Categories() noexcept;
	[[nodiscard]] const Descriptor* Find(std::string_view a_id) noexcept;
}
